name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || 'github-pages' }}
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup TypeScript
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npx tsc

      - name: Generate manifest
        run: node --loader ts-node/esm scripts/generate-manifest.ts

      - name: Copy files
        run: |
          mkdir -p dist
          cp -r guides dist/
          cp src/index.html dist/
          cp src/styles.css dist/

      - name: Debug dist contents
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          echo "Contents of dist/guides directory:"
          ls -la dist/guides/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || '.' }}
          commit_message: ${{ github.event_name == 'pull_request' && format('Deploy PR {0}', github.event.number) || 'Deploy to GitHub Pages' }}
