name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'pull_request' && 'preview' || 'github-pages' }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup TypeScript
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npx tsc

      - name: Generate manifest
        run: node --loader ts-node/esm scripts/generate-manifest.ts

      - name: Prepare deployment files
        run: |
          # Create a clean deployment directory
          rm -rf deploy
          mkdir -p deploy

          # Copy only the necessary files
          cp -r guides deploy/
          cp src/index.html deploy/
          cp src/styles.css deploy/
          cp dist/app.js deploy/

          # Copy utils directory if it exists
          if [ -d "dist/utils" ]; then
            cp -r dist/utils deploy/
          fi

          # Create .nojekyll file
          touch deploy/.nojekyll

      - name: Debug deployment files
        run: |
          echo "Current directory:"
          pwd
          echo "Contents of current directory:"
          ls -la
          echo "Contents of deploy directory:"
          ls -la deploy/
          echo "Contents of deploy/guides directory:"
          ls -la deploy/guides/
          echo "Contents of dist directory:"
          ls -la dist/
          echo "Contents of src directory:"
          ls -la src/

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./deploy"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
          environment_name: ${{ github.event_name == 'pull_request' && 'preview' || 'github-pages' }}
          environment_url: ${{ steps.pages.outputs.base_url }}/${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || '' }}

      - name: Debug deployment output
        run: |
          echo "Deployment output:"
          echo "Destination directory: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || '.' }}"
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Base URL: ${{ steps.pages.outputs.base_url }}"
          echo "Environment URL: ${{ steps.deployment.outputs.page_url }}"
