name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || 'github-pages' }}
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup TypeScript
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npx tsc

      - name: Generate manifest
        run: node --loader ts-node/esm scripts/generate-manifest.ts

      - name: Copy files
        run: |
          mkdir -p dist
          cp -r guides dist/
          cp src/index.html dist/
          cp src/styles.css dist/

      - name: Debug dist contents
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          echo "Contents of dist/guides directory:"
          ls -la dist/guides/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || '.' }}
          commit_message: ${{ github.event_name == 'pull_request' && format('Deploy PR #{0}', github.event.number) || 'Deploy to GitHub Pages' }}

      - name: Debug deployment
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "PR number: ${{ github.event.number }}"
          echo "Destination dir: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || '.' }}"
          echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"

      - name: Set preview URL
        id: preview
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "preview_url=https://how-to-faang-utcn.github.io/How-to-faang-Guide/pr-${{ github.event.number }}/" >> $GITHUB_OUTPUT
          else
            echo "preview_url=https://how-to-faang-utcn.github.io/How-to-faang-Guide/" >> $GITHUB_OUTPUT
          fi
          echo "Setting preview URL to: ${{ steps.preview.outputs.preview_url }}"

      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const previewUrl = '${{ steps.preview.outputs.preview_url }}';
            console.log('Preview URL:', previewUrl);
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '🚀 Preview deployment is ready!\n\nYou can view your changes at: ' + previewUrl + '\n\nNote: It may take a few minutes for the deployment to be available.'
            });
