name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup TypeScript
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npx tsc

      - name: Generate manifest
        run: node --loader ts-node/esm scripts/generate-manifest.ts

      - name: Prepare deployment files
        run: |
          rm -rf deploy
          mkdir -p deploy

          cp -r guides deploy/
          cp src/index.html deploy/
          cp src/styles.css deploy/
          cp dist/app.js deploy/

          if [ -d "dist/utils" ]; then
            cp -r dist/utils deploy/
          fi

          touch deploy/.nojekyll

      - name: Debug deployment files
        run: |
          echo "Contents of deploy directory:"
          ls -la deploy/
          echo "Contents of deploy/guides directory:"
          ls -la deploy/guides/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: gh-pages
          commit_message: "Deploy to GitHub Pages"
          force_orphan: true
          enable_jekyll: false

      - name: Debug deployment
        run: |
          echo "Checking gh-pages branch..."
          git fetch origin gh-pages
          git stash
          git checkout gh-pages
          echo "Contents of gh-pages branch:"
          ls -la
          echo "Checking remote branches:"
          git branch -a
          echo "Checking if gh-pages branch is up to date:"
          git status
